in:
  type: file
  path_prefix: ./example/data
  parser:
    type: csv
    delimiter: "\t"
    skip_header_lines: 0
    null_string: ""
    columns:
      - { name: id, type: long }
      - { name: description, type: string }
      - { name: name, type: string }
      - { name: t, type: timestamp, format: "%Y-%m-%d %H:%M:%S %z"}
      - { name: payload, type: json}
    stop_on_invalid_record: true

filters:
  - type: copy
    copy:
      - name: copy-01
        filters:
          - type: remove_columns
            remove: ["t"]
          - type: copy
            copy:
              - out:
                  type: stdout
        out:
          type: stdout
      - exec:
          max_threads: 4
        filters:
          - type: remove_columns
            remove: ["payload"]
        out:
          type: stdout

out:
  type: stdout
