in:
  type: file
  path_prefix: ./example/data.tsv
  parser:
    type: csv
    delimiter: "\t"
    skip_header_lines: 0
    null_string: ""
    columns:
      - { name: id, type: long }
      - { name: description, type: string }
      - { name: name, type: string }
      - { name: payload, type: json}
    stop_on_invalid_record: true

filters:
  - type: 
      source: maven
      group: io.github.civitaspo
      name: copy
      version: 0.0.3.pre
    config:
      filters:
        - type: remove_columns
          remove: ["id"]
      out:
        type: stdout
      exec:
        max_threads: 8

out:
  type: stdout
